project:
  type: website

website:
  title: "ML-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: ML_notebook.qmd
        text: ML_Notebook

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



